import { eq, and } from "drizzle-orm";
import { db } from "../db/client.js";
import { workoutPlans, planExercises, exercises } from "../db/schema.js";
import PDFDocument from "pdfkit";
import type { Response } from "express";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FONT_REGULAR = join(__dirname, "../assets/fonts/DejaVuSans.ttf");
const FONT_BOLD = join(__dirname, "../assets/fonts/DejaVuSans-Bold.ttf");

export async function listPlans(trainerId: string) {
  const plans = await db
    .select()
    .from(workoutPlans)
    .where(eq(workoutPlans.trainerId, trainerId));
  const planIds = plans.map((p) => p.id);
  if (planIds.length === 0)
    return plans.map((p) => ({ ...p, exerciseNames: [] as string[] }));

  const allRows = await Promise.all(
    planIds.map((id) =>
      db
        .select({ planId: planExercises.planId, name: exercises.name })
        .from(planExercises)
        .innerJoin(exercises, eq(planExercises.exerciseId, exercises.id))
        .where(eq(planExercises.planId, id))
        .orderBy(planExercises.position),
    ),
  );
  const namesByPlan = Object.fromEntries(
    planIds.map((id, i) => [id, allRows[i].map((r) => r.name)]),
  );
  return plans.map((p) => ({ ...p, exerciseNames: namesByPlan[p.id] ?? [] }));
}

export async function getPlan(trainerId: string, planId: string) {
  const [plan] = await db
    .select()
    .from(workoutPlans)
    .where(
      and(eq(workoutPlans.id, planId), eq(workoutPlans.trainerId, trainerId)),
    );
  if (!plan) return null;
  const items = await db
    .select({
      id: planExercises.id,
      position: planExercises.position,
      sets: planExercises.sets,
      reps: planExercises.reps,
      durationSeconds: planExercises.durationSeconds,
      restSeconds: planExercises.restSeconds,
      notes: planExercises.notes,
      exercise: exercises,
    })
    .from(planExercises)
    .innerJoin(exercises, eq(planExercises.exerciseId, exercises.id))
    .where(eq(planExercises.planId, planId))
    .orderBy(planExercises.position);
  return { ...plan, exercises: items };
}

export async function createPlan(
  trainerId: string,
  data: { name: string; description?: string },
) {
  const [plan] = await db
    .insert(workoutPlans)
    .values({ trainerId, ...data })
    .returning();
  return plan;
}

export async function updatePlan(
  trainerId: string,
  planId: string,
  data: Partial<{ name: string; description: string }>,
) {
  const [plan] = await db
    .update(workoutPlans)
    .set({ ...data, updatedAt: new Date() })
    .where(
      and(eq(workoutPlans.id, planId), eq(workoutPlans.trainerId, trainerId)),
    )
    .returning();
  return plan ?? null;
}

export async function deletePlan(trainerId: string, planId: string) {
  const [plan] = await db
    .delete(workoutPlans)
    .where(
      and(eq(workoutPlans.id, planId), eq(workoutPlans.trainerId, trainerId)),
    )
    .returning();
  return plan ?? null;
}

export async function replacePlanExercises(
  trainerId: string,
  planId: string,
  items: Array<{
    exerciseId: string;
    sets?: number;
    reps?: number;
    durationSeconds?: number;
    restSeconds?: number;
    notes?: string;
  }>,
) {
  const plan = await getPlan(trainerId, planId);
  if (!plan) return null;
  await db.delete(planExercises).where(eq(planExercises.planId, planId));
  if (items.length === 0) return [];
  return db
    .insert(planExercises)
    .values(items.map((item, i) => ({ planId, position: i, ...item })))
    .returning();
}

export async function addPlanExercise(
  trainerId: string,
  planId: string,
  data: {
    exerciseId: string;
    sets?: number;
    reps?: number;
    durationSeconds?: number;
    restSeconds?: number;
    notes?: string;
  },
) {
  const plan = await getPlan(trainerId, planId);
  if (!plan) return null;
  const position = plan.exercises.length;
  const [pe] = await db
    .insert(planExercises)
    .values({ planId, position, ...data })
    .returning();
  return pe;
}

export async function removePlanExercise(
  trainerId: string,
  planId: string,
  peId: string,
) {
  const plan = await getPlan(trainerId, planId);
  if (!plan) return null;
  const [pe] = await db
    .delete(planExercises)
    .where(and(eq(planExercises.id, peId), eq(planExercises.planId, planId)))
    .returning();
  return pe ?? null;
}

function addWatermark(doc: InstanceType<typeof PDFDocument>, date: string) {
  const text = `Generated by FitTrainer on ${date}`;
  const savedY = doc.y;
  doc.save();
  doc.opacity(0.07);
  doc.font(FONT_REGULAR).fontSize(26);
  doc.rotate(-45, { origin: [doc.page.width / 2, doc.page.height / 2] });
  doc.fillColor("#000000");
  doc.text(text, 0, doc.page.height / 2 - 13, {
    align: "center",
    width: doc.page.width,
    lineBreak: false,
  });
  doc.restore();
  doc.y = savedY;
  doc.x = doc.page.margins.left;
}

export async function exportPlanAsPdf(
  trainerId: string,
  planId: string,
  res: Response,
  meta?: {
    trainerName?: string;
    trainerEmail?: string;
    trainerPhone?: string;
    client?: { name: string; email?: string | null; phone?: string | null };
  },
) {
  const plan = await getPlan(trainerId, planId);
  if (!plan) return null;

  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const M = 72; // uniform margin on all sides
  const doc = new PDFDocument({ margin: M, autoFirstPage: true });
  doc.registerFont("Regular", FONT_REGULAR);
  doc.registerFont("Bold", FONT_BOLD);

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${plan.name.replace(/[^a-z0-9]/gi, "_")}.pdf"`,
  );
  doc.pipe(res);

  // Start at top margin
  doc.y = doc.page.margins.top;
  addWatermark(doc, date);

  // Trainer branding
  if (meta?.trainerName) {
    doc
      .font("Regular")
      .fontSize(10)
      .fillColor("#9CA3AF")
      .text(`Trainer: ${meta.trainerName}`, { align: "right" });
    if (meta.trainerEmail) {
      doc
        .font("Regular")
        .fontSize(9)
        .fillColor("#9CA3AF")
        .text(meta.trainerEmail, { align: "right" });
    }
    if (meta.trainerPhone) {
      doc
        .font("Regular")
        .fontSize(9)
        .fillColor("#9CA3AF")
        .text(meta.trainerPhone, { align: "right" });
    }
    doc.moveDown(0.5);
  }

  // Client block
  if (meta?.client) {
    doc
      .font("Bold")
      .fontSize(12)
      .fillColor("#374151")
      .text(`Prepared for: ${meta.client.name}`);
    const clientDetails = [meta.client.email, meta.client.phone]
      .filter(Boolean)
      .join("  ·  ");
    if (clientDetails) {
      doc.font("Regular").fontSize(10).fillColor("#6B7280").text(clientDetails);
    }
    doc.moveDown(0.4);
    doc.moveTo(M, doc.y).lineTo(doc.page.width - M, doc.y).strokeColor("#E5E7EB").stroke();
    doc.moveDown(0.6);
  }

  // Plan name and description
  doc.font("Bold").fontSize(22).fillColor("#111827").text(plan.name);
  if (plan.description) {
    doc
      .moveDown(0.4)
      .font("Regular")
      .fontSize(11)
      .fillColor("#6B7280")
      .text(plan.description);
  }

  // Estimated duration
  const totalSeconds = plan.exercises.reduce((sum, pe) => {
    const sets = pe.sets ?? 1;
    const dur = pe.durationSeconds ?? 45;
    const rest = pe.restSeconds ?? 60;
    return sum + sets * (dur + rest);
  }, 0);
  const durationLabel =
    totalSeconds < 60
      ? `${totalSeconds}s`
      : `~${Math.round(totalSeconds / 60)} min`;
  doc
    .moveDown(0.4)
    .font("Regular")
    .fontSize(10)
    .fillColor("#6B7280")
    .text(`Estimated duration: ${durationLabel}`);

  doc.moveDown(1);

  // columns fit within content width: 612 - M*2 = 468pt
  const colX = {
    num:    M,
    name:   M + 22,
    muscle: M + 154,
    sets:   M + 226,
    reps:   M + 258,
    dur:    M + 290,
    rest:   M + 332,
    notes:  M + 374,
  };

  let y = doc.y;
  doc.font("Bold").fontSize(9).fillColor("#374151");
  doc.text("#",        colX.num,    y, { width: 20 });
  doc.text("Exercise", colX.name,   y, { width: 130 });
  doc.text("Muscle",   colX.muscle, y, { width: 70 });
  doc.text("Sets",     colX.sets,   y, { width: 30 });
  doc.text("Reps",     colX.reps,   y, { width: 30 });
  doc.text("Dur(s)",   colX.dur,    y, { width: 40 });
  doc.text("Rest(s)",  colX.rest,   y, { width: 40 });
  doc.text("Notes",    colX.notes,  y, { width: doc.page.width - M - colX.notes });

  doc.moveDown(0.3);
  doc.moveTo(M, doc.y).lineTo(doc.page.width - M, doc.y).strokeColor("#E5E7EB").stroke();
  doc.moveDown(0.3);

  doc.font("Regular").fillColor("#111827");
  for (const [i, pe] of plan.exercises.entries()) {
    if (doc.y > 700) {
      doc.addPage();
      doc.y = doc.page.margins.top;
      addWatermark(doc, date);
    }
    y = doc.y;
    const fmt = (v: number | null | undefined) => (v != null ? String(v) : "—");
    doc.font("Regular").fontSize(9);
    doc.text(String(i + 1),           colX.num,    y, { width: 20 });
    doc.text(pe.exercise.name,        colX.name,   y, { width: 130 });
    doc.text(pe.exercise.muscleGroup, colX.muscle, y, { width: 70 });
    doc.text(fmt(pe.sets),            colX.sets,   y, { width: 30 });
    doc.text(fmt(pe.reps),            colX.reps,   y, { width: 30 });
    doc.text(fmt(pe.durationSeconds), colX.dur,    y, { width: 40 });
    doc.text(fmt(pe.restSeconds),     colX.rest,   y, { width: 40 });
    doc.text(pe.notes ?? "—",         colX.notes,  y, { width: doc.page.width - M - colX.notes });

    if (pe.exercise.description) {
      doc
        .moveDown(0.3)
        .font("Regular")
        .fontSize(8)
        .fillColor("#9CA3AF")
        .text(pe.exercise.description, colX.name, doc.y, { width: 460 });
      doc.fillColor("#111827");
    }
    doc.moveDown(0.5);
  }

  doc.end();
  return true;
}
